/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/accounts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Accounts Endpoint
         * @description Return all accounts that belong to the authenticated user.
         */
        get: operations["list_accounts_endpoint_api_v1_accounts__get"];
        put?: never;
        /**
         * Create Account Endpoint
         * @description Create an account linked to a bank owned by the current user.
         */
        post: operations["create_account_endpoint_api_v1_accounts__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Account Endpoint
         * @description Update an account owned by the authenticated user.
         */
        put: operations["update_account_endpoint_api_v1_accounts__account_id__put"];
        post?: never;
        /**
         * Delete Account Endpoint
         * @description Delete an account owned by the authenticated user.
         */
        delete: operations["delete_account_endpoint_api_v1_accounts__account_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticate user, set cookie, and return access token payload.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Invalidate the current access token so it cannot be reused after logout.
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Current User
         * @description Return the authenticated user profile.
         */
        get: operations["read_current_user_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Current User
         * @description Update the authenticated user's profile fields.
         */
        patch: operations["update_current_user_api_v1_auth_me_patch"];
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Token
         * @description Validate refresh token and issue a new access token payload.
         */
        post: operations["refresh_token_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Register a new user with hashed password.
         */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/banks/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Banks Endpoint
         * @description Return all banks owned by the authenticated user.
         */
        get: operations["list_banks_endpoint_api_v1_banks__get"];
        put?: never;
        /**
         * Create Bank Endpoint
         * @description Create a bank for the authenticated user.
         */
        post: operations["create_bank_endpoint_api_v1_banks__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/banks/{bank_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Bank Endpoint
         * @description Update a bank owned by the authenticated user.
         */
        put: operations["update_bank_endpoint_api_v1_banks__bank_id__put"];
        post?: never;
        /**
         * Delete Bank Endpoint
         * @description Delete a bank owned by the authenticated user.
         */
        delete: operations["delete_bank_endpoint_api_v1_banks__bank_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Categories Endpoint
         * @description Return all global categories (public catalog — no auth required).
         */
        get: operations["list_categories_endpoint_api_v1_categories__get"];
        put?: never;
        /**
         * Create Category Endpoint
         * @description Create a global spending category.
         */
        post: operations["create_category_endpoint_api_v1_categories__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories/{category_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Category Endpoint
         * @description Update a global category.
         */
        put: operations["update_category_endpoint_api_v1_categories__category_id__put"];
        post?: never;
        /**
         * Delete Category Endpoint
         * @description Delete a global category.
         */
        delete: operations["delete_category_endpoint_api_v1_categories__category_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/countries/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Countries Endpoint
         * @description Return all global countries.
         */
        get: operations["list_countries_endpoint_api_v1_countries__get"];
        put?: never;
        /**
         * Create Country Endpoint
         * @description Create a global country entry.
         */
        post: operations["create_country_endpoint_api_v1_countries__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/countries/{country_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Country Endpoint
         * @description Update a global country entry.
         */
        put: operations["update_country_endpoint_api_v1_countries__country_id__put"];
        post?: never;
        /**
         * Delete Country Endpoint
         * @description Delete a global country entry.
         */
        delete: operations["delete_country_endpoint_api_v1_countries__country_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/investment-entities/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Investment Entities Endpoint
         * @description Return all investment entities owned by the authenticated user.
         */
        get: operations["list_investment_entities_endpoint_api_v1_investment_entities__get"];
        put?: never;
        /**
         * Create Investment Entity Endpoint
         * @description Create an investment entity for the authenticated user.
         */
        post: operations["create_investment_entity_endpoint_api_v1_investment_entities__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/investment-entities/{investment_entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Investment Entity Endpoint
         * @description Update an investment entity owned by the authenticated user.
         */
        put: operations["update_investment_entity_endpoint_api_v1_investment_entities__investment_entity_id__put"];
        post?: never;
        /**
         * Delete Investment Entity Endpoint
         * @description Delete an investment entity owned by the authenticated user.
         */
        delete: operations["delete_investment_entity_endpoint_api_v1_investment_entities__investment_entity_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/investments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Investments Endpoint
         * @description Return all investments belonging to the authenticated user.
         */
        get: operations["list_investments_endpoint_api_v1_investments__get"];
        put?: never;
        /**
         * Create Investment Endpoint
         * @description Register a new investment for the authenticated user.
         */
        post: operations["create_investment_endpoint_api_v1_investments__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/investments/{investment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Investment Endpoint
         * @description Return a single investment owned by the authenticated user.
         */
        get: operations["get_investment_endpoint_api_v1_investments__investment_id__get"];
        /**
         * Update Investment Endpoint
         * @description Update an investment owned by the authenticated user.
         */
        put: operations["update_investment_endpoint_api_v1_investments__investment_id__put"];
        post?: never;
        /**
         * Delete Investment Endpoint
         * @description Delete an investment owned by the authenticated user.
         */
        delete: operations["delete_investment_endpoint_api_v1_investments__investment_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/aggregates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Aggregates Endpoint
         * @description Return pre-computed chart data and period totals for the dashboard.
         */
        get: operations["get_aggregates_endpoint_api_v1_metrics_aggregates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Metrics Endpoint
         * @description Return aggregated dashboard metrics in the requested currency.
         */
        get: operations["get_metrics_endpoint_api_v1_metrics_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pockets/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Pockets Endpoint
         * @description Return all pockets that belong to the authenticated user.
         */
        get: operations["list_pockets_endpoint_api_v1_pockets__get"];
        put?: never;
        /**
         * Create Pocket Endpoint
         * @description Create a pocket under an account owned by the authenticated user.
         */
        post: operations["create_pocket_endpoint_api_v1_pockets__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pockets/move-funds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Move Funds To Pocket Endpoint
         * @description Move funds from a user account into a pocket and register expense transaction.
         */
        post: operations["move_funds_to_pocket_endpoint_api_v1_pockets_move_funds_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pockets/{pocket_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Pocket Endpoint
         * @description Return a single pocket owned by the authenticated user.
         */
        get: operations["get_pocket_endpoint_api_v1_pockets__pocket_id__get"];
        /**
         * Update Pocket Endpoint
         * @description Update a pocket owned by the authenticated user.
         */
        put: operations["update_pocket_endpoint_api_v1_pockets__pocket_id__put"];
        post?: never;
        /**
         * Delete Pocket Endpoint
         * @description Delete a pocket owned by the authenticated user.
         */
        delete: operations["delete_pocket_endpoint_api_v1_pockets__pocket_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Transactions Endpoint
         * @description List user transactions with pagination metadata (total, skip, limit).
         */
        get: operations["list_transactions_endpoint_api_v1_transactions__get"];
        put?: never;
        /**
         * Create Transaction Endpoint
         * @description Create a transaction and update account balance accordingly.
         */
        post: operations["create_transaction_endpoint_api_v1_transactions__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Transactions Csv
         * @description Export all matching transactions as a UTF-8 CSV file (no pagination limit).
         */
        get: operations["export_transactions_csv_api_v1_transactions_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions/transfer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Transfer Endpoint
         * @description Create an atomic transfer between two accounts and return both transaction legs.
         */
        post: operations["create_transfer_endpoint_api_v1_transactions_transfer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions/{transaction_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Transaction Endpoint
         * @description Update a transaction and keep balances consistent.
         */
        put: operations["update_transaction_endpoint_api_v1_transactions__transaction_id__put"];
        post?: never;
        /**
         * Delete Transaction Endpoint
         * @description Delete a transaction and reverse its balance effect.
         */
        delete: operations["delete_transaction_endpoint_api_v1_transactions__transaction_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthcheck
         * @description Return lightweight liveness payload for health probes.
         */
        get: operations["healthcheck_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness
         * @description Readiness probe: verifica conectividad real con la BD.
         *
         *     Diferencia clave vs `/health`:
         *     - liveness (/health): ¿el proceso responde? Si falla, k8s reinicia el pod.
         *     - readiness (/ready): ¿puede atender tráfico? Si falla, k8s lo saca del LB.
         */
        get: operations["readiness_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AccountCreate
         * @description Payload used to create a bank account.
         */
        AccountCreate: {
            account_type: components["schemas"]["AccountType"];
            /** Bank Id */
            bank_id: number;
            currency: components["schemas"]["Currency"];
            /**
             * Current Balance
             * @default 0
             */
            current_balance: number | string;
            /** Name */
            name: string;
        };
        /**
         * AccountRead
         * @description Serialized account response exposed by the API.
         */
        AccountRead: {
            account_type: components["schemas"]["AccountType"];
            /** Bank Id */
            bank_id: number;
            currency: components["schemas"]["Currency"];
            /** Current Balance */
            current_balance: number;
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /**
         * AccountType
         * @description Supported bank account types.
         * @enum {string}
         */
        AccountType: "savings" | "checking";
        /**
         * AccountUpdate
         * @description Payload used to update a bank account.
         */
        AccountUpdate: {
            account_type: components["schemas"]["AccountType"];
            /** Bank Id */
            bank_id: number;
            currency: components["schemas"]["Currency"];
            /** Name */
            name: string;
        };
        /**
         * BankCreate
         * @description Payload used to create a bank entity.
         */
        BankCreate: {
            /**
             * Country Code
             * @default CO
             */
            country_code: string;
            /** Name */
            name: string;
        };
        /**
         * BankRead
         * @description Serialized bank response exposed by the API.
         */
        BankRead: {
            /** Country Code */
            country_code: string;
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /**
         * BankUpdate
         * @description Payload used to update a bank entity.
         */
        BankUpdate: {
            /** Country Code */
            country_code: string;
            /** Name */
            name: string;
        };
        /**
         * CategoryCreate
         * @description Payload used to create a custom transaction category.
         */
        CategoryCreate: {
            /**
             * Category Type
             * @default any
             * @enum {string}
             */
            category_type: "income" | "expense" | "any";
            /**
             * Description
             * @description Human-readable description shown in the UI to guide category selection.
             */
            description?: string | null;
            /**
             * Is Fixed
             * @default false
             */
            is_fixed: boolean;
            /** Name */
            name: string;
        };
        /**
         * CategoryExpenseRow
         * @description Total expense and fixed/variable classification for a single category.
         */
        CategoryExpenseRow: {
            /** Is Fixed */
            is_fixed: boolean;
            /** Name */
            name: string;
            /** Value */
            value: number;
        };
        /**
         * CategoryRead
         * @description Serialized category response exposed by the API.
         */
        CategoryRead: {
            /**
             * Category Type
             * @default any
             * @enum {string}
             */
            category_type: "income" | "expense" | "any";
            /** Description */
            description?: string | null;
            /** Id */
            id: number;
            /**
             * Is Fixed
             * @default false
             */
            is_fixed: boolean;
            /** Name */
            name: string;
        };
        /**
         * CategoryUpdate
         * @description Partial update payload for a category.
         */
        CategoryUpdate: {
            /** Category Type */
            category_type?: ("income" | "expense" | "any") | null;
            /** Description */
            description?: string | null;
            /** Is Fixed */
            is_fixed?: boolean | null;
            /** Name */
            name?: string | null;
        };
        /**
         * CountryCreate
         * @description Payload used to create a country entry.
         */
        CountryCreate: {
            /** Code */
            code: string;
            /** Name */
            name: string;
        };
        /**
         * CountryRead
         * @description Serialized country response exposed by the API.
         */
        CountryRead: {
            /** Code */
            code: string;
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /**
         * CountryUpdate
         * @description Partial update payload for a country.
         */
        CountryUpdate: {
            /** Code */
            code?: string | null;
            /** Name */
            name?: string | null;
        };
        /**
         * Currency
         * @description Supported currency codes in the current MVP.
         * @enum {string}
         */
        Currency: "COP" | "USD";
        /**
         * DashboardAggregates
         * @description Pre-computed chart data and period totals for the financial dashboard.
         */
        DashboardAggregates: {
            /** Biggest Expense Amount */
            biggest_expense_amount: number | null;
            /** Biggest Expense Description */
            biggest_expense_description: string | null;
            /** Expenses */
            expenses: number;
            /** Fixed Total */
            fixed_total: number;
            /** Income */
            income: number;
            /** Monthly */
            monthly: components["schemas"]["MonthlyBreakdown"][];
            /** Prev Expenses */
            prev_expenses: number;
            /** Prev Income */
            prev_income: number;
            /** Stacked */
            stacked: components["schemas"]["StackedMonthRow"][];
            /** Stacked Cats */
            stacked_cats: string[];
            /** Top Categories */
            top_categories: components["schemas"]["CategoryExpenseRow"][];
            /** Transaction Count */
            transaction_count: number;
        };
        /**
         * DashboardMetrics
         * @description Aggregated KPI values shown in the financial dashboard.
         */
        DashboardMetrics: {
            /** Cashflow */
            cashflow: number;
            /** Net Worth */
            net_worth: number;
            /** Savings Rate */
            savings_rate: number;
            /** Total Expenses */
            total_expenses: number;
            /** Total Income */
            total_income: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InvestmentCreate
         * @description Payload used to register a new investment position.
         */
        InvestmentCreate: {
            /** Amount Invested */
            amount_invested: number | string;
            currency: components["schemas"]["Currency"];
            /** Current Value */
            current_value: number | string;
            /** Instrument Type */
            instrument_type: string;
            /** Investment Entity Id */
            investment_entity_id: number;
            /** Name */
            name: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
        };
        /**
         * InvestmentEntityCreate
         * @description Payload used to create an investment entity.
         */
        InvestmentEntityCreate: {
            /**
             * Country Code
             * @default CO
             */
            country_code: string;
            entity_type: components["schemas"]["InvestmentEntityType"];
            /** Name */
            name: string;
        };
        /**
         * InvestmentEntityRead
         * @description Serialized investment entity response exposed by the API.
         */
        InvestmentEntityRead: {
            /** Country Code */
            country_code: string;
            entity_type: components["schemas"]["InvestmentEntityType"];
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /**
         * InvestmentEntityType
         * @description Supported entity categories where investments can be held.
         * @enum {string}
         */
        InvestmentEntityType: "bank" | "broker" | "exchange" | "fund_manager" | "other";
        /**
         * InvestmentEntityUpdate
         * @description Payload used to update an investment entity.
         */
        InvestmentEntityUpdate: {
            /** Country Code */
            country_code: string;
            entity_type: components["schemas"]["InvestmentEntityType"];
            /** Name */
            name: string;
        };
        /**
         * InvestmentRead
         * @description Serialized investment response exposed by the API.
         */
        InvestmentRead: {
            /** Amount Invested */
            amount_invested: number;
            currency: components["schemas"]["Currency"];
            /** Current Value */
            current_value: number;
            /** Id */
            id: number;
            /** Instrument Type */
            instrument_type: string;
            /** Investment Entity Id */
            investment_entity_id: number;
            /** Name */
            name: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
        };
        /**
         * InvestmentUpdate
         * @description Payload used to update an existing investment position.
         */
        InvestmentUpdate: {
            /** Current Value */
            current_value: number | string;
            /** Instrument Type */
            instrument_type: string;
            /** Investment Entity Id */
            investment_entity_id: number;
            /** Name */
            name: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
        };
        /**
         * MonthlyBreakdown
         * @description Income, expense, cashflow and running cumulative for a single calendar month.
         */
        MonthlyBreakdown: {
            /** Cashflow */
            cashflow: number;
            /** Cumulative */
            cumulative: number;
            /** Expense */
            expense: number;
            /** Income */
            income: number;
            /** Month */
            month: string;
        };
        /**
         * PocketCreate
         * @description Payload used to create a pocket inside an account.
         */
        PocketCreate: {
            /** Account Id */
            account_id: number;
            /**
             * Balance
             * @default 0
             */
            balance: number | string;
            currency: components["schemas"]["Currency"];
            /** Name */
            name: string;
        };
        /**
         * PocketMoveCreate
         * @description Payload used to move funds from account balance into a pocket.
         */
        PocketMoveCreate: {
            /** Account Id */
            account_id: number;
            /** Amount */
            amount: number | string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Pocket Id */
            pocket_id: number;
        };
        /**
         * PocketRead
         * @description Serialized pocket response exposed by the API.
         */
        PocketRead: {
            /** Account Id */
            account_id: number;
            /** Balance */
            balance: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            currency: components["schemas"]["Currency"];
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /**
         * PocketUpdate
         * @description Payload used to update an existing pocket.
         */
        PocketUpdate: {
            /** Account Id */
            account_id: number;
            /** Name */
            name: string;
        };
        /**
         * StackedMonthRow
         * @description Per-month expense breakdown keyed by category name (for stacked charts).
         */
        StackedMonthRow: {
            /** Categories */
            categories: {
                [key: string]: string;
            };
            /** Month */
            month: string;
        };
        /**
         * Token
         * @description JWT access token payload returned by auth endpoints.
         */
        Token: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /**
         * TransactionCreate
         * @description Payload used to create or update a transaction.
         */
        TransactionCreate: {
            /** Account Id */
            account_id: number;
            /** Amount */
            amount: number | string;
            /** Category Id */
            category_id?: number | null;
            currency: components["schemas"]["Currency"];
            /** Description */
            description: string;
            /**
             * Is Initial Balance
             * @default false
             */
            is_initial_balance: boolean;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Pocket Id */
            pocket_id?: number | null;
            transaction_type: components["schemas"]["TransactionType"];
        };
        /**
         * TransactionPage
         * @description Paginated list of transactions with total count for UI pagination controls.
         */
        TransactionPage: {
            /** Items */
            items: components["schemas"]["TransactionRead"][];
            /** Limit */
            limit: number;
            /** Skip */
            skip: number;
            /** Total */
            total: number;
        };
        /**
         * TransactionRead
         * @description Serialized transaction response exposed by the API.
         */
        TransactionRead: {
            /** Account Id */
            account_id: number;
            /** Amount */
            amount: number;
            /** Category Id */
            category_id: number | null;
            currency: components["schemas"]["Currency"];
            /** Description */
            description: string;
            /** Id */
            id: number;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Pocket Id */
            pocket_id: number | null;
            transaction_type: components["schemas"]["TransactionType"];
        };
        /**
         * TransactionType
         * @description Transaction direction that impacts account balance.
         * @enum {string}
         */
        TransactionType: "income" | "expense";
        /**
         * TransferCreate
         * @description Payload for creating an atomic transfer between two accounts.
         */
        TransferCreate: {
            /** Amount */
            amount: number | string;
            /** From Account Id */
            from_account_id: number;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** To Account Id */
            to_account_id: number;
        };
        /**
         * UserCreate
         * @description Payload used to register a new user.
         */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name: string;
            /** Password */
            password: string;
        };
        /**
         * UserLogin
         * @description Credentials payload used to authenticate users.
         */
        UserLogin: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * UserRead
         * @description Public user representation returned by API responses.
         */
        UserRead: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name: string;
            /** Id */
            id: number;
        };
        /**
         * UserUpdate
         * @description Fields the user may update on their own profile.
         */
        UserUpdate: {
            /** Current Password */
            current_password?: string | null;
            /** Email */
            email?: string | null;
            /** Full Name */
            full_name?: string | null;
            /** New Password */
            new_password?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_accounts_endpoint_api_v1_accounts__get: {
        parameters: {
            query?: {
                search?: string | null;
                account_type?: components["schemas"]["AccountType"] | null;
                currency?: components["schemas"]["Currency"] | null;
                bank_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_account_endpoint_api_v1_accounts__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_account_endpoint_api_v1_accounts__account_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_account_endpoint_api_v1_accounts__account_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserLogin"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_current_user_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_current_user_api_v1_auth_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_token_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie: {
                refresh_token: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_banks_endpoint_api_v1_banks__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_bank_endpoint_api_v1_banks__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BankCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_bank_endpoint_api_v1_banks__bank_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bank_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BankUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_bank_endpoint_api_v1_banks__bank_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bank_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_categories_endpoint_api_v1_categories__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryRead"][];
                };
            };
        };
    };
    create_category_endpoint_api_v1_categories__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_category_endpoint_api_v1_categories__category_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_category_endpoint_api_v1_categories__category_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_countries_endpoint_api_v1_countries__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CountryRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_country_endpoint_api_v1_countries__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CountryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CountryRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_country_endpoint_api_v1_countries__country_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                country_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CountryUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CountryRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_country_endpoint_api_v1_countries__country_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                country_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_investment_entities_endpoint_api_v1_investment_entities__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestmentEntityRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_investment_entity_endpoint_api_v1_investment_entities__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvestmentEntityCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestmentEntityRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_investment_entity_endpoint_api_v1_investment_entities__investment_entity_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investment_entity_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvestmentEntityUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestmentEntityRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_investment_entity_endpoint_api_v1_investment_entities__investment_entity_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investment_entity_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_investments_endpoint_api_v1_investments__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestmentRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_investment_endpoint_api_v1_investments__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvestmentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestmentRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_investment_endpoint_api_v1_investments__investment_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investment_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestmentRead"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_investment_endpoint_api_v1_investments__investment_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investment_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvestmentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestmentRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_investment_endpoint_api_v1_investments__investment_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investment_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_aggregates_endpoint_api_v1_metrics_aggregates_get: {
        parameters: {
            query: {
                start_date: string;
                end_date: string;
                prev_start_date: string;
                prev_end_date: string;
                currency?: string;
            };
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardAggregates"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_metrics_endpoint_api_v1_metrics_dashboard_get: {
        parameters: {
            query?: {
                currency?: string;
            };
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardMetrics"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_pockets_endpoint_api_v1_pockets__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PocketRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_pocket_endpoint_api_v1_pockets__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PocketCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PocketRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    move_funds_to_pocket_endpoint_api_v1_pockets_move_funds_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PocketMoveCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pocket_endpoint_api_v1_pockets__pocket_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pocket_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PocketRead"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_pocket_endpoint_api_v1_pockets__pocket_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pocket_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PocketUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PocketRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_pocket_endpoint_api_v1_pockets__pocket_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pocket_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_transactions_endpoint_api_v1_transactions__get: {
        parameters: {
            query?: {
                start_date?: string | null;
                end_date?: string | null;
                account_id?: number | null;
                transaction_type?: components["schemas"]["TransactionType"] | null;
                currency?: components["schemas"]["Currency"] | null;
                search?: string | null;
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_transaction_endpoint_api_v1_transactions__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_transactions_csv_api_v1_transactions_export_get: {
        parameters: {
            query?: {
                start_date?: string | null;
                end_date?: string | null;
                account_id?: number | null;
                transaction_type?: components["schemas"]["TransactionType"] | null;
                currency?: components["schemas"]["Currency"] | null;
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_transfer_endpoint_api_v1_transactions_transfer_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransferCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionRead"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_transaction_endpoint_api_v1_transactions__transaction_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_transaction_endpoint_api_v1_transactions__transaction_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthcheck_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readiness_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
